
# Use official Python image
FROM python:3.11-slim

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV PROJECT_ROOT=/app

# Set working directory
WORKDIR $PROJECT_ROOT


# Install dependencies
COPY requirements.txt ./requirements.txt
RUN pip install -r requirements.txt

# Copy the entire project into the container
COPY . .

# Make sure the chroma_db directory exists
RUN mkdir -p chroma_db

# Copy the chroma_db from your repo into the container
COPY ../chroma_db ./chroma_db

# Expose port for Flask
EXPOSE 5000

# Command to run Flask app
CMD ["gunicorn", "main:app"]
